name: Bug report
description: Create a report to help us improve
title: "[Bug]: Short description of the issue"
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug.
      placeholder: Provide a clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. First Step
        2. Second Step
        3. and so on...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please add any other relevant information about the bug and remove the unnecessary lines.
      placeholder: |
        - Linux Distro: [e.g., ArchLinux, EndeavourOS]
        - Linux Version, output of `uname -a`:
        - Hyprland Version, output of `hyprctl version`:
        - Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
        - Other info: [e.g., Display Resolution, Resolution, etc]
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other information about the problem here.
      placeholder: Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.
    validations:
      required: false
